// NLE-003: Broken link on /careers
// Generated by Nomad Loop Engine. Run: npx playwright test nle-003.spec.ts
import { test, expect } from '@playwright/test';

test("NLE-003: Broken link on /careers", async ({ page }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  const docStatuses: number[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', (res) => {
    if (res.request().isNavigationRequest()) docStatuses.push(res.status());
    else if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`);
  });
  await page.goto("http://localhost:4100/careers");
  expect(docStatuses.every((s) => s < 400), `document statuses: ${docStatuses}`).toBe(true);
});
