// Turns anomalies into bug reports: human repro steps, a standalone Playwright test that
// reproduces the bug, a screenshot, and an N-run replay that separates real bugs from flakes.
import type { Browser } from 'playwright-core';
import { checkState, correlate, PageMonitor } from './anomaly';
import { gotoAndSettle, NavStatus, perform, toHealEvent } from './executor';
import type { SelfHealingLocator } from './locator';
import { snapshot } from './snapshot';
import type { Action, Anomaly, AnomalyType, BugReport, HealEvent, ReproRecipe, SweepItem } from '@nomad/contracts';

export type { ReproRecipe };

const TITLES: Record<AnomalyType, string> = {
  server_error: 'Server error',
  broken_link: 'Broken link',
  console_error: 'Console error',
  page_error: 'Uncaught exception',
  network_failure: 'Failed API request',
  broken_image: 'Broken image',
  suspicious_text: 'Suspicious text',
  slow_response: 'Slow API response',
  llm_judged: 'Behaviour judged incorrect',
};

export function bugTitle(a: Anomaly, recipe: ReproRecipe): string {
  const where = new URL(a.url).pathname;
  const via = recipe.action ? ` after “${recipe.action.target?.name || recipe.action.label}”` : '';
  return `${TITLES[a.type]} on ${where}${via}`;
}

const q = (s: string) => JSON.stringify(s);

function roleLocator(a: Action): string {
  const t = a.target!;
  if ((t.role === 'link' || t.role === 'button') && t.name)
    return `page.getByRole(${q(t.role)}, { name: ${q(t.name)}, exact: true }).first()`;
  return `page.locator(${q(t.cssPath)}).first()`;
}

/** Generates a standalone @playwright/test file that fails while the bug exists. */
export function reproScript(bugId: string, title: string, anomaly: Anomaly, r: ReproRecipe): string {
  const lines: string[] = [];
  lines.push(`// ${bugId}: ${title}`);
  lines.push(`// Generated by Nomad Loop Engine. Run: npx playwright test ${bugId.toLowerCase()}.spec.ts`);
  lines.push(`import { test, expect } from '@playwright/test';`, '');
  lines.push(`test(${q(`${bugId}: ${title}`)}, async ({ page }) => {`);
  lines.push(`  const errors: string[] = [];`);
  lines.push(`  const failed: string[] = [];`);
  lines.push(`  const docStatuses: number[] = [];`);
  lines.push(`  page.on('pageerror', (e) => errors.push(e.message));`);
  lines.push(`  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });`);
  lines.push(`  page.on('response', (res) => {`);
  lines.push(`    if (res.request().isNavigationRequest()) docStatuses.push(res.status());`);
  lines.push(`    else if (res.status() >= 400) failed.push(\`\${res.status()} \${res.url()}\`);`);
  lines.push(`  });`);
  if (anomaly.type === 'slow_response') {
    const path = anomaly.message.split(' ')[1] || '/';
    lines.push(`  const t0 = Date.now();`);
    lines.push(`  const slow = page.waitForResponse((res) => res.url().includes(${q(path)}));`);
  }
  lines.push(`  await page.goto(${q(r.fromUrl)});`);
  if (r.action?.target) {
    const a = r.action;
    if (a.kind === 'fill_submit' || a.kind === 'fill_submit_empty') {
      lines.push(`  const form = ${roleLocator(a)}.locator('xpath=ancestor::form[1]');`);
      for (const f of a.fields || []) {
        if (!f.name || f.type === 'checkbox' || f.type === 'radio') continue;
        const v = a.kind === 'fill_submit' ? (r.values[f.name] ?? '') : '';
        lines.push(`  await form.locator(${q(`[name="${f.name}"]`)}).fill(${q(v)});`);
      }
    }
    lines.push(`  await ${roleLocator(a)}.click();`);
    lines.push(`  await page.waitForLoadState('networkidle');`);
  }
  switch (anomaly.type) {
    case 'server_error':
    case 'broken_link':
      lines.push(`  expect(docStatuses.every((s) => s < 400), \`document statuses: \${docStatuses}\`).toBe(true);`);
      break;
    case 'network_failure':
    case 'broken_image':
      lines.push(`  expect(failed).toEqual([]);`);
      break;
    case 'console_error':
    case 'page_error':
      lines.push(`  expect(errors).toEqual([]);`);
      break;
    case 'suspicious_text': {
      const token = (anomaly.message.match(/“(.+?)”/) || [])[1] || 'NaN';
      lines.push(`  await expect(page.locator('body')).not.toContainText(${q(token)});`);
      break;
    }
    case 'slow_response':
      lines.push(`  await slow;`);
      lines.push(`  expect(Date.now() - t0).toBeLessThan(3000);`);
      break;
    case 'llm_judged':
      lines.push(`  // Judged incorrect by the local LLM: ${anomaly.message.replace(/\n/g, ' ')}`);
      lines.push(`  // An invalid submission should keep the user on the form with a validation message.`);
      lines.push(`  expect(new URL(page.url()).pathname).toBe(${q(new URL(r.fromUrl).pathname)});`);
      lines.push(`  await expect(page.getByText(/placed|success|thank/i)).toHaveCount(0);`);
      break;
  }
  lines.push(`});`, '');
  return lines.join('\n');
}

/**
 * Replays a recipe N times in fresh browser contexts and counts how often the same anomaly
 * signature reappears. >= ceil(N/2) → confirmed, 1+ → flaky, 0 → unverified.
 */
export interface VerifyResult {
  hits: number;
  status: BugReport['status'];
  /** Locator outcomes from the first replay: shows whether selectors had to heal. */
  heals: HealEvent[];
}

export async function verify(
  browser: Browser,
  recipe: ReproRecipe,
  anomaly: Anomaly,
  locator: SelfHealingLocator,
  runs = 3,
): Promise<VerifyResult> {
  if (anomaly.type === 'llm_judged') return { hits: 0, status: 'unverified', heals: [] }; // judged once; replay needs the LLM
  let hits = 0;
  let heals: HealEvent[] = [];
  for (let i = 0; i < runs; i++) {
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    try {
      const monitor = new PageMonitor(page);
      const nav = new NavStatus(page);
      let status = await gotoAndSettle(page, recipe.fromUrl, nav);
      if (recipe.action) {
        monitor.drain();
        const res = await perform(page, recipe.action, recipe.values, locator, nav);
        if (i === 0 && recipe.action.target) heals = [toHealEvent(0, recipe.action.target, res.heal)];
        status = res.status;
      }
      const seen = correlate([...monitor.drain(), ...checkState(await snapshot(page, status))]);
      if (seen.some((s) => s.signature === anomaly.signature)) hits++;
    } catch {
      // a failed replay simply does not count as a hit
    } finally {
      await ctx.close();
    }
  }
  const status = hits >= Math.ceil(runs / 2) ? 'confirmed' : hits > 0 ? 'flaky' : 'unverified';
  return { hits, status, heals };
}

/**
 * Repro minimization: if simply loading the page where the anomaly showed up reproduces it,
 * that one-line recipe wins over replaying the action (and does not depend on app state).
 */
export async function minimizeAndVerify(
  browser: Browser,
  full: ReproRecipe,
  anomaly: Anomaly,
  locator: SelfHealingLocator,
  runs = 3,
): Promise<{ recipe: ReproRecipe; hits: number; runs: number; status: BugReport['status'] }> {
  if (full.action && anomaly.type !== 'llm_judged') {
    const minimal: ReproRecipe = { fromUrl: anomaly.url, action: null, values: {} };
    const probe = await verify(browser, minimal, anomaly, locator, 1);
    if (probe.hits === 1) {
      const rest = await verify(browser, minimal, anomaly, locator, runs - 1);
      const hits = 1 + rest.hits;
      return { recipe: minimal, hits, runs, status: hits >= Math.ceil(runs / 2) ? 'confirmed' : 'flaky' };
    }
  }
  const v = await verify(browser, full, anomaly, locator, runs);
  return { recipe: full, hits: v.hits, runs, status: v.status };
}

/** Moves a URL onto another build's origin, keeping path and query. */
export function rebase(url: string, targetOrigin: string): string {
  const u = new URL(url);
  return new URL(u.pathname + u.search, targetOrigin).toString();
}

/**
 * Regression sweep: replays every bug of an earlier run against another build (a fix, a redesign)
 * through the self-healing locator, and reports which bugs are still there.
 */
export async function sweepBugs(
  browser: Browser,
  bugs: BugReport[],
  targetUrl: string,
  locator: SelfHealingLocator,
  runs = 3,
  onItem?: (item: SweepItem) => void,
): Promise<SweepItem[]> {
  const origin = new URL(targetUrl).origin;
  const items: SweepItem[] = [];
  for (const bug of bugs) {
    if (bug.type === 'llm_judged') continue;
    const recipe: ReproRecipe = { ...bug.recipe, fromUrl: rebase(bug.recipe.fromUrl, origin) };
    const anomaly: Anomaly = {
      type: bug.type,
      message: bug.message,
      url: rebase(bug.url, origin),
      signature: bug.signature,
      severity: bug.severity,
    };
    const v = await verify(browser, recipe, anomaly, locator, runs);
    const item: SweepItem = {
      bugId: bug.id,
      title: bug.title,
      severity: bug.severity,
      verdict: v.hits === 0 ? 'fixed' : v.status === 'confirmed' ? 'still broken' : 'flaky',
      reproduced: `${v.hits}/${runs}`,
      replayedOn: recipe.fromUrl,
      heals: v.heals,
    };
    items.push(item);
    onItem?.(item);
  }
  return items;
}
