// NLE-007: Failed API request on /product/3 after “Add to cart”
// Generated by Nomad Loop Engine. Run: npx playwright test nle-007.spec.ts
import { test, expect } from '@playwright/test';

test("NLE-007: Failed API request on /product/3 after “Add to cart”", async ({ page }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  const docStatuses: number[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', (res) => {
    if (res.request().isNavigationRequest()) docStatuses.push(res.status());
    else if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`);
  });
  await page.goto("http://localhost:4100/product/3");
  await page.getByRole("button", { name: "Add to cart", exact: true }).first().click();
  await page.waitForLoadState('networkidle');
  expect(failed).toEqual([]);
});
