// NLE-004: Suspicious text on /newsletter after “Subscribe”
// Generated by Nomad Loop Engine. Run: npx playwright test nle-004.spec.ts
import { test, expect } from '@playwright/test';

test("NLE-004: Suspicious text on /newsletter after “Subscribe”", async ({ page }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  const docStatuses: number[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', (res) => {
    if (res.request().isNavigationRequest()) docStatuses.push(res.status());
    else if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`);
  });
  await page.goto("http://localhost:4100/search?q=Subscribe");
  const form = page.getByRole("button", { name: "Subscribe", exact: true }).first().locator('xpath=ancestor::form[1]');
  await form.locator("[name=\"email\"]").fill("nomad.tester@example.com");
  await page.getByRole("button", { name: "Subscribe", exact: true }).first().click();
  await page.waitForLoadState('networkidle');
  await expect(page.locator('body')).not.toContainText("[object Object]");
});
