// NLE-009: Uncaught exception on /cart after “Apply coupon”
// Generated by Nomad Loop Engine. Run: npx playwright test nle-009.spec.ts
import { test, expect } from '@playwright/test';

test("NLE-009: Uncaught exception on /cart after “Apply coupon”", async ({ page }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  const docStatuses: number[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', (res) => {
    if (res.request().isNavigationRequest()) docStatuses.push(res.status());
    else if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`);
  });
  await page.goto("http://localhost:4100/cart?removed=1");
  await page.getByRole("button", { name: "Apply coupon", exact: true }).first().click();
  await page.waitForLoadState('networkidle');
  expect(errors).toEqual([]);
});
