// NLE-002: Slow API response on /
// Generated by Nomad Loop Engine. Run: npx playwright test nle-002.spec.ts
import { test, expect } from '@playwright/test';

test("NLE-002: Slow API response on /", async ({ page }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  const docStatuses: number[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', (res) => {
    if (res.request().isNavigationRequest()) docStatuses.push(res.status());
    else if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`);
  });
  const t0 = Date.now();
  const slow = page.waitForResponse((res) => res.url().includes("/api/recommendations"));
  await page.goto("http://localhost:4100");
  await slow;
  expect(Date.now() - t0).toBeLessThan(3000);
});
